import type { Metadata } from "next";
import localFont from "next/font/local";
import {Nunito} from "next/font/google";
import "./globals.css";

export const nunito = Nunito({
  subsets: ['latin'],
  variable: "--font-nunito",
  weight: "400",
});

const geistMono = localFont({
  src: "./fonts/Nunito-BoldItalic.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${geistMono.variable} antialiased bg-backgroundColor min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
