import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { Roboto } from 'next/font/google'

export const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: '400',
})

// const geistMono = localFont({
//   src: './fonts/roboto-BoldItalic.ttf',
//   variable: '--font-geist-mono',
//   weight: '100 900',
// })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${roboto.className}  antialiased bg-backgroundColor min-h-screen`}
      >
        {children}
      </body>
    </html>
  )
}
